apiVersion: v1
kind: Service
metadata:
  name: webapps-service
spec:
  type: NodePort
  selector:
    app: my-webapps
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
